# Generated by Django 4.2.27 on 2026-02-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_evidence_id_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='source',
            field=models.CharField(choices=[('UPLOAD', 'Subido por usuario'), ('PORTAL', 'Documento del portal')], default='UPLOAD', max_length=20),
        ),
    ]
